Pull request Registers
rafacc1414/RISC-V pull request #1
Opened 2021-04-26 19:56 UTC by rafacc1414

2021-05-01 12:14 UTC, sm13 requested changes

2021-05-01 12:14 UTC, sm13 commented on Registers/register_file.vhd
> +	end process READ;
@rafacc1414 I see that the read process is asynchronous. If that is by design, add that to the little documentation.

2021-05-01 12:14 UTC, sm13 commented on Registers/register_file.vhd
> +			read_validity <= '0';
Line 42 and this one are a problem. We should never assign a signal in two different processes (there's only one exception that I can think of). This makes it very difficult for a computer to model the behavior. It is also very prone to errors. In essence, you are asking the tool to both:
- Create a 'wire' called `read_validity` which is set to `1`,
- Create a register called `read_validity` which is cleared on the falling_edge of the clock.

You should do one of two things:

1. Integrate the logic from Line 42 into this process.
2. Make the signal in Line 42, and the one here different. Then use the signal in Line 42 to set the logic here.

2021-05-01 12:14 UTC, sm13 commented on Registers/register_file.vhd
> +
You should add a comment in this line to summarize what this does. For instance:
``` vhdl
-- Implement a bank of 32 32-bit RISC V registers. Two registers can be read at
-- once via the signals rs1, rs2. The outputs are placed on rd1, rd2.
 ```

2021-05-01 12:14 UTC, sm13 commented on Registers/register_file.vhd
> +		if (falling_edge(CLK)) then
This should probably be rising_edge. It could be OK to use the falling edge, it just makes it a little harder for the tools to make this work.

 Why do you want to use the falling edge?

2021-05-01 21:46 UTC, rafacc1414 commented on Registers/register_file.vhd
> +	end process READ;
Yes, it is asynchronous by design.

2021-05-01 22:03 UTC, rafacc1414 commented on Registers/register_file.vhd
> +			read_validity <= '0';
Honestly, I think we should remove read_validity. This shrunk of code were written one day while Juanmi and me were debating about how to do the synchronization with the ALU to unify everything. However, I do not see the aim of getting a signal which tell us when the read process is done. Because the read process is asynchronous and it is going to be done any time rs1 or  rs2 change.

2021-05-01 22:07 UTC, rafacc1414 commented on Registers/register_file.vhd
> +		if (falling_edge(CLK)) then
As I said in the other comment, I think we must remove read_validity_process

2021-05-01 22:17 UTC, rafacc1414 commented on Registers/register_file.vhd
> +
I have modified the file and I have written the following text. 

-- Implement a bank of 32 32-bit RISC V registers. Two registers can be read at
-- once via the signals rs1, rs2. The outputs are placed on rd1, rd2.
-- To write in a register, 'we' must be equal to one. Then, 'ws' will select the 
-- register which will be written and 'wd' will contain the data to write in 
-- the selected registers

2021-05-02 19:05 UTC, sm13 commented on Registers/register_file.vhd
> +			read_validity <= '0';
OK. Discuss if @juanmi1001 agrees, delete it.

2021-05-02 19:06 UTC, sm13 commented on Registers/register_file.vhd
> +
Add all changes to a commit and I'll "approve" the merge.

2021-05-03 14:03 UTC, juanmi1001 commented on Registers/register_file.vhd
> +			read_validity <= '0';
Yes, I think that we have implemented wrongly the synchronization (use of read_validity). We have to discuss it how to do it correctly. 
Because we're sure that it is needed to implement a signal to the RISCV controller (from the registers) to know when the value obtained from the registers is valid, so that value can be send it to the ALU to do the operation.

2021-05-03 20:09 UTC, sm13 commented on Registers/register_file.vhd
> +			read_validity <= '0';
@juanmi1001 as @rafacc1414 said you know when you get the results based on when you read. Do the simplest and easy thing.

2021-05-03 20:17 UTC, juanmi1001 commented on Registers/register_file.vhd
> +			read_validity <= '0';
Yes, that's it that we have been discussing today, the controller doesnt need the read validity signal, knowing the design, it only needs to wait one cycle to be sure that the value at the registers is the useful for this iteration. 

We'll try tomorrow to do a fix on it, modifying registers and controller.

2021-05-04 09:12 UTC, rafacc1414 commented on Registers/register_file.vhd
> +			read_validity <= '0';
read_validity removed

2021-05-10 19:16 UTC, merged